[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlx = {version="0.8.6", features=["sqlite", "runtime-tokio"]}
tokio = {version="1.45.0", features=["full"]}
warp = "0.3.7"
