[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
rand = "0.9.1"
serde = "1.0.219"
serde_json = "1.0.140"
sqlx = {version="0.8.6", features=["sqlite", "runtime-tokio"]}
tokio = {version="1.45.0", features=["full"]}
warp = "0.3.7"
